// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4DmoIwZinSotowxzqtfLGGd2DDFSGmlc',
    appId: '1:82684076359:web:4a9493de0207fcddb26c62',
    messagingSenderId: '82684076359',
    projectId: 'unicharge-c6d5c',
    authDomain: 'unicharge-c6d5c.firebaseapp.com',
    storageBucket: 'unicharge-c6d5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw6fNDK9Hy9c73wzPUKabWT-KhmHw08ws',
    appId: '1:82684076359:android:b60324afab97efe8b26c62',
    messagingSenderId: '82684076359',
    projectId: 'unicharge-c6d5c',
    storageBucket: 'unicharge-c6d5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8CxVknQzbse0tA4qH1dHin1QLBaUQZW0',
    appId: '1:82684076359:ios:5cfaeb8122a62257b26c62',
    messagingSenderId: '82684076359',
    projectId: 'unicharge-c6d5c',
    storageBucket: 'unicharge-c6d5c.firebasestorage.app',
    iosBundleId: 'com.unemployednerds.unicharge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8CxVknQzbse0tA4qH1dHin1QLBaUQZW0',
    appId: '1:82684076359:ios:88df4ea9cd52e3bab26c62',
    messagingSenderId: '82684076359',
    projectId: 'unicharge-c6d5c',
    storageBucket: 'unicharge-c6d5c.firebasestorage.app',
    iosBundleId: 'com.example.parkcharge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4DmoIwZinSotowxzqtfLGGd2DDFSGmlc',
    appId: '1:82684076359:web:4f3bdd340846c8edb26c62',
    messagingSenderId: '82684076359',
    projectId: 'unicharge-c6d5c',
    authDomain: 'unicharge-c6d5c.firebaseapp.com',
    storageBucket: 'unicharge-c6d5c.firebasestorage.app',
  );
}
